### ISSUE TITLE
Getting Blank Screen from SDK. 

### ISSUE THREAD

**Issue by Paras3112** [postpayio/react-native-postpay-widget#1]
We are using your payment gateway but in this we have used your demo but we are facing issue of blank scree. 

Please let us know what is the problem with SDK. 

We have pass required details from our end. 

Please take a look of below video for the same. 

Video - https://drive.google.com/file/d/1xTpXoo49OdGtlvxPCdwoa3xT8pYf_Hwr/view?usp=sharing

Also, As per SDK requirement we need to pass widget URL so we are passing this "https://sandbox.postpay.io/" it is correct or not? Or Do we need to do something here like create HTML page or something else here?

Please guide us on this thing. 

Thanks in advance.

**Comment by minhchienwikipedia** [comment]
Related https://github.com/postpayio/react-native-postpay-widget-example/issues/1#issuecomment-1125792683
